name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**

env:
  project: TuviPgpLib.sln
  test-project: TuviPgpLib.sln
  dotnet-version: 8.x

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup dotnet
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Build
      run: dotnet build ${{ env.project }} --configuration ${{ env.configuration }}
        
    - name: Test
      if: env.test-project != ''
      run: dotnet test ${{ env.test-project }} --configuration ${{ env.configuration }}
