name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**

env:
  project: TuviPgpLib.sln
  test-project: TuviPgpLib.sln
  dotnet-version: 8.x

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup dotnet
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Build
      run: dotnet build ${{ env.project }} --configuration ${{ env.configuration }}
        
    - name: Test
      if: env.test-project != ''
      run: dotnet test ${{ env.test-project }} --configuration ${{ env.configuration }}
